export const users = [
  {
    id: "a14f9cc2b3617490e17b951c2155360d",
    firstName: "Alexandr",
    lastName: "Hamabrdzumyan",
    phone: "notDefined",
    email: "alexanhambarcumyan@gmail.com",
    education: "Shushi Technology university",
    workExperience: "AIPC",
    trainings: "RELQ school",
  },
  {
    id: "fa412f7ef1b69b6ae84a74ebfb67aec6",
    firstName: "Anahit",
    lastName: "Khechumyan",
    phone: "notDefined",
    email: "Khechumyan63@gmail.com",
    education: "Yerevan State University",
    workExperience: "School Principal-School N67 Bitschool",
    trainings: "RELQ",
  },
  {
    id: "f3bd14f1fb018f6af820f437e5230197",
    firstName: "Ani",
    lastName: "Antonyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "RELQ",
  },
  {
    id: "9f03bd1d9084276aa6c66175ec16e5be",
    firstName: "Anna",
    lastName: "Hayriyan",
    phone: "notDefined",
    email: "annhayriyan@gmail.com",
    education: "ASUE",
    workExperience: "Scott logistics",
    trainings: "RELQ",
  },
  {
    id: "97d0b6df5353be8eccfc5f514c485f2d",
    firstName: "Armenak",
    lastName: "Qocharyan",
    phone: "notDefined",
    email: "qocharyanarmenak@gmail.com",
    education: "Բարձրագույն զինվորական",
    workExperience: "ՀՀ ՊՆ",
    trainings: "Relq School",
  },
  {
    id: "95e2eace1abd317bba2e4fc17a8d76d6",
    firstName: "Arusyak",
    lastName: "Aghajanyan",
    phone: "notDefined",
    email: "aghajanyanarusyak@gmail.com",
    education: "YSUGU",
    workExperience: "InecoBank CJSC, Risk meneger",
    trainings:
      "BasicItCenter,UNDP Armenia Accelerator5,HTI Armenia C++ basic, SmartCode,Relq Technology",
  },
  {
    id: "8370396fd739e2e093d16950f418fdd7",
    firstName: "Afina",
    lastName: "Panyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq",
  },
  {
    id: "868ae86d7f021c14b5eeecb979a3fe1b",
    firstName: "Babken",
    lastName: "Tadevosyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq",
  },
  {
    id: "8e615a14f6d00018bd4bb30742237703",
    firstName: "Hasmik",
    lastName: "Gevorgyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq",
  },
  {
    id: "eb8c073c843ecb25c5bc447ccf6923ac",
    firstName: "Hermine",
    lastName: "Melkumyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq",
  },
  {
    id: "dfa3218e22c38ad3de6c06f9e405bc84",
    firstName: "Hermine",
    lastName: "Sahakyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq",
  },
  {
    id: "d102f32b0e6c8cdffcaee28caf8e1ed9",
    firstName: "Larine",
    lastName: "Danielyan",
    phone: "notDefined",
    email: "danielyanlari@gmail.com",
    education: "Economics and Menegment",
    workExperience: "Martuninsky district Medical Association",
    trainings: "Relq",
  },
  {
    id: "e48b6457f6a0afbe9b265bee2caaef6e",
    firstName: "Liana",
    lastName: "Dashyan",
    phone: "notDefined",
    email: "dashyanlian@gmail.com",
    education: "YSU",
    workExperience: "GYU NGO",
    trainings: "Relq",
  },
  {
    id: "e20139c9b3270e2d8522238bd4d1d7a6",
    firstName: "Lusine",
    lastName: "Yeremyan",
    phone: "notDefined",
    email: "lusineer@gmail.com",
    education: "Economist",
    workExperience: "Municipality",
    trainings: "Relq, MIC",
  },
  {
    id: "fd225a34e5e55164c3ab74d4562c0426",
    firstName: "Lusine",
    lastName: "Petrosyan",
    phone: "notDefined",
    email: "plusine99@gmail.com",
    education: "Armenian State University faculty of Radiophysics",
    workExperience: "notDefined",
    trainings: "Relq",
  },
  {
    id: "96542debe4a68a23c51b3b0d346b0bb2",
    firstName: "Karen",
    lastName: "Darbinyan",
    phone: "notDefined",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
  },
  {
    id: "c8171083c631f6a1c3f565ecb6ced6be",
    firstName: "Marat",
    lastName: "Harutyunyan",
    phone: "notDefined",
    email: "maratharutyunyan.mh.mh@gmail.com",
    education: "ASIPCS",
    workExperience: "EL Market",
    trainings: "Relq School",
  },
  {
    id: "b6234c757e826ca7d0060bca351eecaf",
    firstName: "Narek",
    lastName: "Tovmasyan",
    phone: "notDefined",
    email: "Narektom333@gmail.com",
    education: "ASUE",
    workExperience: "Ameria Bank",
    trainings: "Relq School",
  },
  {
    id: "b60538356ddb669a8cbf9761467342ee",
    firstName: "Seda",
    lastName: "Shahnazaryan",
    phone: "notDefined",
    email: "shahnazaryan.seda@mail.ru",
    education: "Higher Education:Historian",
    workExperience: "notDefined",
    trainings: "TechBoost4Women,RELQ technology school",
  },
  {
    id: "8b77b39d673af1c6f5d5fa3de644ed30",
    firstName: "Seryozha",
    lastName: "Asatryan",
    phone: "notDefined",
    email: "seryozha.asatryan02@gmail.com",
    education: "Economics",
    workExperience: "notDefined",
    trainings: "Relq School",
  },
  {
    id: "afac0edf1246feebcb135187fd156a77",
    firstName: "Sevak",
    lastName: "Stepanyan",
    phone: "notDefined",
    email: "stepanyansevak9@gamil.com",
    education: "Economics and Menegment",
    workExperience: "notDefined",
    trainings: "Relq School",
  },
  {
    id: "8eeb304566ad8df19955c984fde4e9bb",
    firstName: "Silva",
    lastName: "Ohanyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq School",
  },
  {
    id: "aeb2f2bc70b3a9f9b428fd4af1d162a6",
    firstName: "Suren",
    lastName: "Galstyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq School",
  },
  {
    id: "a7fbea8172f515d8b22f93d61a7bca7a",
    firstName: "Tigran",
    lastName: "Martirosyan",
    phone: "notDefined",
    email: "martirosyant01@mail.ru",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq School",
  },
];
